In [ ]:
from google.colab import files
files.upload()

Saving Train.zip to Train.zip


In [ ]:
pwd

'/content'

In [ ]:
!unzip Train.zip -d /content/

Archive:  Train.zip
mapname:  conversion of  failed
   creating: /content/Fearow/
   creating: /content/Meowth/
   creating: /content/Dratini/
   creating: /content/Pikachu/
   creating: /content/Psyduck/
   creating: /content/Spearow/
   creating: /content/Squirtle/
   creating: /content/Bulbasaur/
   creating: /content/Aerodactyl/
   creating: /content/Charmander/
 extracting: /content/Pikachu/00000000.jpg  
 extracting: /content/Pikachu/00000001.png  
 extracting: /content/Pikachu/00000002.png  
 extracting: /content/Pikachu/00000003.jpg  
 extracting: /content/Pikachu/00000004.jpg  
 extracting: /content/Pikachu/00000006.png  
 extracting: /content/Pikachu/00000007.jpg  
 extracting: /content/Pikachu/00000009.png  
 extracting: /content/Pikachu/00000010.png  
 extracting: /content/Pikachu/00000011.png  
 extracting: /content/Pikachu/00000013.png  
 extracting: /content/Pikachu/00000014.png  
 extracting: /content/Pikachu/00000015.png  
 extracting: /content/Pikachu/00000016.jpg  
 

In [ ]:
import os
from keras.preprocessing import image

folders = os.listdir('Train')

image_data = []
labels = []
count = 0

for ix in folders:
  path = os.path.join("Train", ix)
  print(path, count)
  for im in os.listdir(path):
    try:
      img = image.load_img(os.path.join(path,im), target_size=(224,224))
      img_array = image.img_to_array(img)
      image_data.append(img_array)
      labels.append(count)
    except:
      pass
  count += 1

Train/Aerodactyl 0
Train/Meowth 1
Train/Bulbasaur 2
Train/Psyduck 3
Train/Squirtle 4
Train/Spearow 5
Train/Fearow 6
Train/Dratini 7
Train/Charmander 8


/usr/local/lib/python3.10/dist-packages/PIL/Image.py:1056: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(


Train/Pikachu 9


In [ ]:
import random

combined_dataset = list(zip(image_data, labels))
random.shuffle(combined_dataset)
image_data[:], labels[:] = zip(*combined_dataset)

In [ ]:
import numpy as np
from keras.utils import to_categorical
X_train=np.array(image_data)
Y_train=np.array(labels)

Y_train = to_categorical(Y_train)
print(Y_train)

[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]]


In [ ]:
# from tensorflow.keras.applications.resnet50 import ResNet50
from tensorflow.keras.applications.mobilenet import MobileNet
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import *
from tensorflow.keras.models import Model
import numpy as np

model = MobileNet(include_top= False, weights= 'imagenet', input_shape=(224,224,3))
print(model.summary())


17225924/17225924 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


Model: "mobilenet_1.00_224"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)           │ (None, 224, 224, 3)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv1 (Conv2D)                       │ (None, 112, 112, 32)        │             864 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv1_bn (BatchNormalization)        │ (None, 112, 112, 32)        │             128 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv1_relu (ReLU)                    │ (None, 112, 112, 32)        │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_dw_1 (DepthwiseConv2D)          │ (None, 112, 112, 32)        │             288 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_dw_1_bn (BatchNormalization)    │ (None, 112, 112, 32)        │             128 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_dw_1_relu (ReLU)                │ (None, 112, 112, 32)        │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_pw_1 (Conv2D)                   │ (None, 112, 112, 64)        │           2,048 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_pw_1_bn (BatchNormalization)    │ (None, 112, 112, 64)        │             256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_pw_1_relu (ReLU)                │ (None, 112, 112, 64)        │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_pad_2 (ZeroPadding2D)           │ (None, 113, 113, 64)        │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_dw_2 (DepthwiseConv2D)          │ (None, 56, 56, 64)          │             576 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_dw_2_bn (BatchNormalization)    │ (None, 56, 56, 64)          │             256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_dw_2_relu (ReLU)                │ (None, 56, 56, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_pw_2 (Conv2D)                   │ (None, 56, 56, 128)         │           8,192 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_pw_2_bn (BatchNormalization)    │ (None, 56, 56, 128)         │             512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_pw_2_relu (ReLU)                │ (None, 56, 56, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_dw_3 (DepthwiseConv2D)          │ (None, 56, 56, 128)         │           1,152 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_dw_3_bn (BatchNormalization)    │ (None, 56, 56, 128)         │             512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_dw_3_relu (ReLU)                │ (None, 56, 56, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_pw_3 (Conv2D)                   │ (None, 56, 56, 128)         │          16,384 │
├──────────────────────────────────────┼─────────────────────────────┼──────────────

 Total params: 3,228,864 (12.32 MB)

 Trainable params: 3,206,976 (12.23 MB)

 Non-trainable params: 21,888 (85.50 KB)

None


In [ ]:
av1 = GlobalAveragePooling2D()(model.output)

fc1 = Dense(256, activation='relu')(av1)

d1 = Dropout(0.5)(fc1)

# fc2 = Dense(128, activation='relu')(d1)

# d2 = Dropout(0.5)(fc2)

# fc3 = Dense(64, activation='relu')(d2)

# d3 = Dropout(0.5)(fc3)

fc4 = Dense(10, activation='softmax')(d1)

In [ ]:
model_new = Model(inputs = model.input, outputs = fc4)
model_new.summary()

Model: "functional_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)           │ (None, 224, 224, 3)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv1 (Conv2D)                       │ (None, 112, 112, 32)        │             864 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv1_bn (BatchNormalization)        │ (None, 112, 112, 32)        │             128 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv1_relu (ReLU)                    │ (None, 112, 112, 32)        │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_dw_1 (DepthwiseConv2D)          │ (None, 112, 112, 32)        │             288 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_dw_1_bn (BatchNormalization)    │ (None, 112, 112, 32)        │             128 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_dw_1_relu (ReLU)                │ (None, 112, 112, 32)        │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_pw_1 (Conv2D)                   │ (None, 112, 112, 64)        │           2,048 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_pw_1_bn (BatchNormalization)    │ (None, 112, 112, 64)        │             256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_pw_1_relu (ReLU)                │ (None, 112, 112, 64)        │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_pad_2 (ZeroPadding2D)           │ (None, 113, 113, 64)        │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_dw_2 (DepthwiseConv2D)          │ (None, 56, 56, 64)          │             576 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_dw_2_bn (BatchNormalization)    │ (None, 56, 56, 64)          │             256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_dw_2_relu (ReLU)                │ (None, 56, 56, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_pw_2 (Conv2D)                   │ (None, 56, 56, 128)         │           8,192 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_pw_2_bn (BatchNormalization)    │ (None, 56, 56, 128)         │             512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_pw_2_relu (ReLU)                │ (None, 56, 56, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_dw_3 (DepthwiseConv2D)          │ (None, 56, 56, 128)         │           1,152 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_dw_3_bn (BatchNormalization)    │ (None, 56, 56, 128)         │             512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_dw_3_relu (ReLU)                │ (None, 56, 56, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_pw_3 (Conv2D)                   │ (None, 56, 56, 128)         │          16,384 │
├──────────────────────────────────────┼─────────────────────────────┼──────────────

 Total params: 3,493,834 (13.33 MB)

 Trainable params: 1,317,642 (5.03 MB)

 Non-trainable params: 2,176,192 (8.30 MB)

In [ ]:
adam = Adam(learning_rate=0.00003)
model_new.compile(loss='categorical_crossentropy', optimizer=adam, metrics=['accuracy'])

In [ ]:
for ix in range(len(model_new.layers)):
  print(ix, model_new.layers[ix])

0 <InputLayer name=input_layer_1, built=True>
1 <Conv2D name=conv1, built=True>
2 <BatchNormalization name=conv1_bn, built=True>
3 <ReLU name=conv1_relu, built=True>
4 <DepthwiseConv2D name=conv_dw_1, built=True>
5 <BatchNormalization name=conv_dw_1_bn, built=True>
6 <ReLU name=conv_dw_1_relu, built=True>
7 <Conv2D name=conv_pw_1, built=True>
8 <BatchNormalization name=conv_pw_1_bn, built=True>
9 <ReLU name=conv_pw_1_relu, built=True>
10 <ZeroPadding2D name=conv_pad_2, built=True>
11 <DepthwiseConv2D name=conv_dw_2, built=True>
12 <BatchNormalization name=conv_dw_2_bn, built=True>
13 <ReLU name=conv_dw_2_relu, built=True>
14 <Conv2D name=conv_pw_2, built=True>
15 <BatchNormalization name=conv_pw_2_bn, built=True>
16 <ReLU name=conv_pw_2_relu, built=True>
17 <DepthwiseConv2D name=conv_dw_3, built=True>
18 <BatchNormalization name=conv_dw_3_bn, built=True>
19 <ReLU name=conv_dw_3_relu, built=True>
20 <Conv2D name=conv_pw_3, built=True>
21 <BatchNormalization name=conv_pw_3_bn, built=True

In [ ]:
for ix in range(72):
  model_new.layers[ix].trainable = False

print(model_new.summary())

Model: "functional_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)           │ (None, 224, 224, 3)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv1 (Conv2D)                       │ (None, 112, 112, 32)        │             864 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv1_bn (BatchNormalization)        │ (None, 112, 112, 32)        │             128 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv1_relu (ReLU)                    │ (None, 112, 112, 32)        │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_dw_1 (DepthwiseConv2D)          │ (None, 112, 112, 32)        │             288 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_dw_1_bn (BatchNormalization)    │ (None, 112, 112, 32)        │             128 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_dw_1_relu (ReLU)                │ (None, 112, 112, 32)        │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_pw_1 (Conv2D)                   │ (None, 112, 112, 64)        │           2,048 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_pw_1_bn (BatchNormalization)    │ (None, 112, 112, 64)        │             256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_pw_1_relu (ReLU)                │ (None, 112, 112, 64)        │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_pad_2 (ZeroPadding2D)           │ (None, 113, 113, 64)        │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_dw_2 (DepthwiseConv2D)          │ (None, 56, 56, 64)          │             576 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_dw_2_bn (BatchNormalization)    │ (None, 56, 56, 64)          │             256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_dw_2_relu (ReLU)                │ (None, 56, 56, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_pw_2 (Conv2D)                   │ (None, 56, 56, 128)         │           8,192 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_pw_2_bn (BatchNormalization)    │ (None, 56, 56, 128)         │             512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_pw_2_relu (ReLU)                │ (None, 56, 56, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_dw_3 (DepthwiseConv2D)          │ (None, 56, 56, 128)         │           1,152 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_dw_3_bn (BatchNormalization)    │ (None, 56, 56, 128)         │             512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_dw_3_relu (ReLU)                │ (None, 56, 56, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv_pw_3 (Conv2D)                   │ (None, 56, 56, 128)         │          16,384 │
├──────────────────────────────────────┼─────────────────────────────┼──────────────

 Total params: 3,493,834 (13.33 MB)

 Trainable params: 1,317,642 (5.03 MB)

 Non-trainable params: 2,176,192 (8.30 MB)

None


In [ ]:
hist = model_new.fit(X_train, Y_train, shuffle= True, batch_size=16, epochs=8, validation_split=0.20)

Epoch 1/8
83/83 ━━━━━━━━━━━━━━━━━━━━ 94s 1s/step - accuracy: 0.1513 - loss: 2.7470 - val_accuracy: 0.4286 - val_loss: 1.7652
Epoch 2/8
83/83 ━━━━━━━━━━━━━━━━━━━━ 132s 955ms/step - accuracy: 0.3432 - loss: 1.9552 - val_accuracy: 0.5441 - val_loss: 1.4459
Epoch 3/8
83/83 ━━━━━━━━━━━━━━━━━━━━ 82s 951ms/step - accuracy: 0.4807 - loss: 1.5351 - val_accuracy: 0.5897 - val_loss: 1.2615
Epoch 4/8
83/83 ━━━━━━━━━━━━━━━━━━━━ 84s 965ms/step - accuracy: 0.5699 - loss: 1.3007 - val_accuracy: 0.6383 - val_loss: 1.1280
Epoch 5/8
83/83 ━━━━━━━━━━━━━━━━━━━━ 81s 961ms/step - accuracy: 0.6478 - loss: 1.1542 - val_accuracy: 0.6960 - val_loss: 1.0327
Epoch 6/8
83/83 ━━━━━━━━━━━━━━━━━━━━ 82s 968ms/step - accuracy: 0.6863 - loss: 1.0024 - val_accuracy: 0.7264 - val_loss: 0.9539
Epoch 7/8
83/83 ━━━━━━━━━━━━━━━━━━━━ 78s 943ms/step - accuracy: 0.7025 - loss: 0.9386 - val_accuracy: 0.7234 - val_loss: 0.8945
Epoch 8/8
83/83 ━━━━━━━━━━━━━━━━━━━━ 82s 945ms/step - accuracy: 0.7378 - loss: 0.8620 - val_accuracy: 0.74

In [ ]:
# from keras.applications.resnet50 import preprocess_input
from keras.applications.mobilenet import preprocess_input

image_path = 'pikachu1.png'
img = image.load_img(image_path, target_size=(224,224))
x = image.img_to_array(img)
x = np.expand_dims(x,axis=0)
x = preprocess_input(x)

pred = model_new.predict(x)
print(pred)
print(np.argmax(pred))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
[[2.2746176e-04 7.8578515e-04 5.6646176e-04 1.6686823e-03 5.4938765e-04
  1.0218419e-03 1.5276216e-04 7.4188370e-05 5.6411292e-02 9.3854213e-01]]
9
